version: "3.8"
services:
  mysql:
    image: mysql
    environment:
      mysql_PASSWORD: dbosupreme
      mysql_DB: dbosupreme

    healthcheck:
      test: ["CMD-SHELL", "mysql_isready -U postgres"]
      interval: 10s
      timeout: 15s
      retries: 5

    ports:
      - 5432:5432

    networks:
      - dbosupreme-dev-network

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ../:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 5432
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: dbosupreme
      MYSQL_DATABASE: dbosupreme

    ports:
      - 3333:3333

    networks:
      - dbosupreme-dev-network

    depends_on:
      mysql:
        condition: service_healthy

networks:
  dbosupreme-dev-network:
    driver: 'bridge'


